// Generated by LiveScript 1.4.0
/*
getLocation = (callback) ->
  sendBackground 'getLocation', {}, (location) ->
    console.log 'got location'
    console.log location

sendBackground = (type, data, callback) ->
  console.log 'sendBackground sent: '
  console.log type
  console.log data
  chrome.runtime.sendMessage {type, data}, (response) ->
    console.log 'got response!'
    callback response
*/
(function(){
  var getLocation, getTabInfo;
  getLocation = function(callback){
    return getTabInfo(function(tabinfo){
      return callback(tabinfo.url);
    });
  };
  getTabInfo = function(callback){
    return chrome.tabs.query({
      active: true,
      lastFocusedWindow: true
    }, function(tabs){
      if (tabs.length === 0) {
        return;
      }
      return chrome.tabs.get(tabs[0].id, callback);
    });
  };
  $(document).ready(function(){
    $('#open_options_page').click(function(){
      return chrome.runtime.openOptionsPage();
    });
    return function(){
      console.log('message sent askdfjl!');
      return getLocation(function(location){
        var ref$, hostname, path;
        console.log('received location');
        console.log(location);
        ref$ = new URL("/aa/bb/", location), hostname = ref$.hostname, path = ref$.path;
        $('#sitename').text(hostname);
        return list_available_experiments_for_location(location, function(possible_experiments){
          return get_experiments(function(all_experiments){
            var i$, ref$, len$, experiment_name, experiment_info, results$ = [];
            console.log(possible_experiments);
            for (i$ = 0, len$ = (ref$ = possible_experiments).length; i$ < len$; ++i$) {
              experiment_name = ref$[i$];
              experiment_info = all_experiments[experiment_name];
              results$.push($('#experiment_list').append(experiment_info.title));
            }
            return results$;
          });
        });
      });
    }();
  });
}).call(this);
